<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <UserSecretsId>b8ec8040-9973-474c-94d7-e176cb44a562</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CodeArt.Optimizely.HeadlessKit\CodeArt.Optimizely.HeadlessKit.csproj" />
  </ItemGroup>

</Project>
